version: '3.8'
services:
  app:
    build:
      context: .
    ports: 
      - 8080:8080
    restart: on-failure
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: ["mongod", "--notablescan"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
